# -*- coding: utf-8 -*-
"""Ciclos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JPS57dI-nnWG6BTak9ZJCIo9Bi11SUde

1. Escribir un programa que pregunte al usuario una cantidad a invertir, el interés anual y
el número de años, y muestre por pantalla el capital obtenido en la inversión cada año
que dura la inversión.
"""

cantidad = float(input("Introduce la cantidad a invertir: "))

interes = float(input("Introduce el interés anual (en porcentaje): "))

anios = int(input("Introduce el número de años: "))

for i in range(anios + 1):
  capital = cantidad * (1 + interes/100)**i
  print(f"Año {i}: {capital:.2f}")

"""2. Escribir un programa que pida al usuario un número entero y muestre por pantalla un
triángulo rectángulo como el de más abajo, de altura el número introducido.
*
**
***
****

*****
"""

numero = int(input("Introduzca la altura del triángulo: "))

for i in range(1, numero + 1):
    print("*" * i)

"""3. Escribir un programa que pida al usuario un número entero y muestre por pantalla un
triángulo rectángulo como el de más abajo.
1
3 1
5 3 1
7 5 3 1
9 7 5 3 1
"""

numero = int(input("Introduzca la altura del triángulo: "))

for i in range(1, numero + 1):
    for j in range(1, i + 1):
        print(2 * j - 1, end=" ")
    print()

"""4. Escribir un programa en el que se pregunte al usuario por una frase y una letra, y
muestre por pantalla el número de veces que aparece la letra en la frase.
"""

frase = input("Introduzca una frase: ")
letra = input("Introduzca una letra: ")

contador = 0
for i in range(len(frase)):
    if frase[i] == letra:
        contador += 1

print(f"La letra '{letra}' aparece {contador} veces en la frase.")

def mostrar_letras_inversas(palabra):
    for letra in palabra[::-1]:
        print(letra)

def main():
    palabra = input("Ingrese una palabra: ")
    mostrar_letras_inversas(palabra)

main()

def main():
    asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
    notas = []

    for asignatura in asignaturas:
        nota = input("Ingrese la nota que ha sacado en {}: ".format(asignatura))
        notas.append(nota)

    for i in range(len(asignaturas)):
        print("En {} has sacado {}".format(asignaturas[i], notas[i]))

main()

def main():
    creditos_asignaturas = {'Matemáticas': 6, 'Física': 4, 'Química': 5}
    for asignatura, creditos in creditos_asignaturas.items():
        print("{} tiene {} créditos".format(asignatura, creditos))
    total_creditos = sum(creditos_asignaturas.values())
    print("El número total de créditos del curso es:", total_creditos)

main()

def calcular_total_factura(cantidad_sin_iva, porcentaje_iva=21):
    total_factura = cantidad_sin_iva * (1 + porcentaje_iva / 100)
    return total_factura
total_con_iva = calcular_total_factura(100)
print("Total de la factura con IVA (21%):", total_con_iva)
total_con_iva_personalizado = calcular_total_factura(100, 10)
print("Total de la factura con IVA personalizado (10%):", total_con_iva_personalizado)

def decimal_a_binario(decimal):
    if decimal == 0:
        return '0'

    binario = ''
    while decimal > 0:
        residuo = decimal % 2
        binario = str(residuo) + binario
        decimal //= 2

    return binario

def binario_a_decimal(binario):
    decimal = 0
    longitud = len(binario)
    for i in range(longitud):
        bit = int(binario[longitud - i - 1])
        decimal += bit * (2 ** i)

    return decimal
numero_decimal = 42
numero_binario = decimal_a_binario(numero_decimal)
print("El número decimal", numero_decimal, "en binario es:", numero_binario)

numero_decimal_nuevo = binario_a_decimal(numero_binario)
print("El número binario", numero_binario, "en decimal es:", numero_decimal_nuevo)

def contar_palabras(cadena):
    palabras = cadena.split()
    frecuencia_palabras = {}
    for palabra in palabras:
        frecuencia_palabras[palabra] = frecuencia_palabras.get(palabra, 0) + 1
    return frecuencia_palabras

def palabra_mas_repetida(diccionario):
    palabra_max = max(diccionario, key=diccionario.get)
    frecuencia_max = diccionario[palabra_max]
    return (palabra_max, frecuencia_max)
def main():
    cadena = input("Ingrese una cadena de caracteres: ")
    frecuencia_palabras = contar_palabras(cadena)
    print("Diccionario de frecuencia de palabras:", frecuencia_palabras)

    palabra_max, frecuencia_max = palabra_mas_repetida(frecuencia_palabras)
    print("La palabra más repetida es '{}' con una frecuencia de {}.".format(palabra_max, frecuencia_max))
main()