# -*- coding: utf-8 -*-
"""Condicionales

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/106TGMg9oGjln_MDyY9oaDOoqWsU2CyPI

1. Escribir una función que reciba la edad y muestre por pantalla si es mayor de edad o
no.
"""

def es_mayor_de_edad(edad):

  if edad >= 18:
    return True
  else:
    return False

edad = int(input("Introduzca su edad: "))

if es_mayor_de_edad(edad):
  print("Eres mayor de edad")
else:
  print("Eres menor de edad")

"""2. Escribir una función que reciba una cadena de caracteres contraseña en una variable, pregunte al usuario por la contraseña e imprima por pantalla si la contraseña introducida por el usuario coincide con la guardada en la variable sin tener en cuenta mayúsculas y minúsculas."""

def validar_contrasena(contrasena):

  contrasena_introducida = input("Introduzca la contraseña: ")
  return contrasena_introducida.lower() == contrasena.lower()

contrasena = "Mipalabraclave"

if validar_contrasena(contrasena):
  print("La contraseña es correcta.")
else:
  print("La contraseña es incorrecta.")

"""3. Para tributar un determinado impuesto se debe ser mayor de 16 años y tener unos ingresos iguales o superiores a 1000 € mensuales. Escribir un programa que pregunte al usuario su edad y sus ingresos mensuales y muestre por pantalla si el usuario tiene que tributar o no."""

edad = int(input("Introduzca su edad: "))
ingresos_mensuales = float(input("Introduzca sus ingresos mensuales: "))

mayor_edad = edad >= 18
ingresos_suficientes = ingresos_mensuales >= 1050

if mayor_edad and ingresos_suficientes:
    print("Sí, tiene que tributar.")
else:
    print("No, no tiene que tributar.")

"""
4. Los alumnos de un curso se han dividido en dos grupos A y B de acuerdo al sexo y el nombre. El grupo A está formado por las mujeres con un nombre anterior a la M y los hombres con un nombre posterior a la N y el grupo B por el resto. Escribir un programa que pregunte al usuario su nombre y sexo, y muestre por pantalla el grupo que le corresponde.
"""

def determinar_grupo(nombre, sexo):

  nombre = nombre.lower()

  if (sexo == "M" and nombre < "m") or (sexo == "H" and nombre > "n"):
    return "A"
  else:
    return "B"

nombre = input("Introduzca su nombre: ")
sexo = input("Introduzca su sexo (M/H): ")

grupo = determinar_grupo(nombre, sexo)

print(f"Usted pertenece al grupo {grupo}")

"""5. En una determinada empresa, sus empleados son evaluados al final de cada año. Los
puntos que pueden obtener en la evaluación comienzan en 0.0 y pueden ir aumentando,
traduciéndose en mejores beneficios. Los puntos que pueden conseguir los empleados
pueden ser 0.0, 0.4, 0.6 o más, pero no valores intermedios entre las cifras
mencionadas. A continuación se muestra una tabla con los niveles correspondientes a
cada puntuación. La cantidad de dinero conseguida en cada nivel es de 2.400€
multiplicada por la puntuación del nivel.
Nivel Puntuación
Inaceptable 0.0
Aceptable 0.4
Meritorio 0.6 o más
Escribir un programa que lea la puntuación del usuario e indique su nivel de
rendimiento, así como la cantidad de dinero que recibirá el usuario.
"""

def evaluar_rendimiento(puntuacion):

  nivel = "Inaceptable"
  dinero = 0.0

  if puntuacion == 0.0:
    nivel = "Inaceptable"
  elif puntuacion == 0.4:
    nivel = "Aceptable"
    dinero = 2400 * 0.4
  elif puntuacion >= 0.6:
    nivel = "Meritorio"
    dinero = 2400 * 0.6
  else:
    pass

  return nivel, dinero

puntuacion = float(input("Introduzca su puntuación: "))
nivel, dinero = evaluar_rendimiento(puntuacion)

print(f"Su nivel de rendimiento es: {nivel}")
print(f"La cantidad de dinero que recibirá es: {dinero:.2f}€")

"""6. Escribir un programa para una empresa que tiene salas de juegos para todas las
edades y quiere calcular de forma automática el precio que debe cobrar a sus clientes
por entrar. El programa debe preguntar al usuario la edad del cliente y mostrar el precio
de la entrada. Si el cliente es menor de 4 años puede entrar gratis, si tiene entre 4 y 18
años debe pagar 5 y si es mayor de 18 años, 10.
"""

edad = int(input("Introduce tu edad: "))

if edad < 4:
    precio = 0
elif edad <= 18:
    precio = 5
else:
    precio = 10

print("El precio de la entrada es", precio, "€.")

"""7. La pizzería Bella Napoli ofrece pizzas vegetarianas y no vegetarianas a sus clientes.
Los ingredientes para cada tipo de pizza aparecen a continuación.
Ingredientes vegetarianos: Pimiento y tofu.
Ingredientes no vegetarianos: Peperoni, Jamón y Salmón.Escribir un programa que pregunte al usuario si quiere una pizza vegetariana o no, y en
función de su respuesta le muestre un menú con los ingredientes disponibles para que
elija. Solo se puede elegir un ingrediente además de la mozzarella y el tomate que
están en todas las pizzas. Al final se debe mostrar por pantalla si la pizza elegida es
vegetariana o no y todos los ingredientes que lleva.
"""

ingredientes_vegetarianos = ["Pimiento", "Tofu"]
ingredientes_no_vegetarianos = ["Peperoni", "Jamón", "Salmón"]

es_vegetariana = input("¿Quieres una pizza vegetariana? (Sí/No): ").lower()

if es_vegetariana == "sí":
    print("**Ingredientes vegetarianos:**")
    for ingrediente in ingredientes_vegetarianos:
        print(f"- {ingrediente}")
else:
    print("**Ingredientes no vegetarianos:**")
    for ingrediente in ingredientes_no_vegetarianos:
        print(f"- {ingrediente}")

ingrediente_elegido = input("Elige un ingrediente adicional: ")

print(f"\n**Resumen de tu pedido:**")
print(f"- Pizza {'vegetariana' if es_vegetariana else 'no vegetariana'}")
print(f"- Mozzarella")
print(f"- Tomate")
print(f"- {ingrediente_elegido}")