# -*- coding: utf-8 -*-
"""Uso de cadenas o strings

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LkMbt-WsJjXulW-JbxFvMWQI4MvI94kZ

Ejercicio1:Escribir una función que reciba el nombre del usuario y un número entero e imprima por
pantalla en líneas distintas el nombre del usuario tantas veces como el número
introducido.
"""

def imprimir_nombre(usuario, repeticiones):
    for _ in range(repeticiones):
        print(usuario)

nombre = input("Ingrese su nombre: ")
numero = int(input("Ingrese un número entero: "))

imprimir_nombre(nombre, numero)

"""Ejercicio2:Escribir una función que reciba el nombre completo del usuario y después muestre por
pantalla el nombre completo del usuario tres veces, una con todas las letras minúsculas,
otra con todas las letras mayúsculas y otra solo con la primera letra del nombre y de los
apellidos en mayúscula. El usuario puede introducir su nombre combinando mayúsculas
y minúsculas como quiera.
"""

def mostrar_nombres(nombre_completo):
    nombre_min = nombre_completo.lower()
    nombre_may = nombre_completo.upper()
    nombre_cap = nombre_completo.title()

    print("Nombre en minúsculas:", nombre_min)
    print("Nombre en mayúsculas:", nombre_may)
    print("Nombre con mayúsculas en la primera letra de cada palabra:", nombre_cap)

nombre_usuario = input("Ingrese su nombre completo: ")

mostrar_nombres(nombre_usuario)

"""Ejercicio3:Escribir una función que reciba el nombre del usuario y después muestre por pantalla
<NOMBRE> tiene <n> letras, donde <NOMBRE> es el nombre de usuario en
mayúsculas y <n> es el número de letras que tienen el nombre.
"""

def mostrar_info_nombre(nombre):
    nombre_en_mayusculas = nombre.upper()
    numero_letras = len(nombre)
    print(f"{nombre_en_mayusculas} tiene {numero_letras} letras.")

nombre_usuario = input("Ingresa tu nombre: ")
mostrar_info_nombre(nombre_usuario)

"""Ejercicio4:Los teléfonos de una empresa tienen el siguiente formato prefijo-número-extensión
donde el prefijo es el código del país +34, y la extensión tiene dos dígitos (por ejemplo
+34-913724710-56). Escribir una función que reciba número de teléfono con este
formato y muestre por pantalla el número de teléfono sin el prefijo y la extensión.
"""

def obtener_numero_telefono(numero_completo):

  prefijo, resto = numero_completo.split("-", 1)

  extension = resto.split(";", 1)[-1] if ";" in resto else None

  numero_sin_extension = resto.split(";", 1)[0]

  return numero_sin_extension

numero_completo = "+54 11 4567-8901;123"
numero_sin_prefijo_extension = obtener_numero_telefono(numero_completo)

print(f"Número sin prefijo ni extensión: {numero_sin_prefijo_extension}")

"""5. Escribir una función que reciba una frase y muestre por pantalla la frase invertida."""

def invertir_frase(frase):
  palabras = frase.split()
  palabras.reverse()
  frase_invertida = " ".join(palabras)
  return frase_invertida

frase = input("digite su frase")
frase_invertida = invertir_frase(frase)
print(f"Frase original: {frase}")
print(f"Frase invertida: {frase_invertida}")